"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import Providers from "@/providers/providers";
import Header from "@/components/common/Header";
import { OTPFlowProvider } from "@/context/otp.context";
import { useUser } from "@/hooks/useUser";
import { usePathname, useRouter } from "next/navigation";
import { useEffect } from "react";
import { Loader } from "@/components/common/Loader";
import UserLayout from "./UserLayout";

// import ThemeLayout from "./(user)/ThemeLayout";
// import Header from "@/components/common/header-ag";


const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

import { AuthProvider, useAuth } from "@/context/auth.context";

function AuthWrapper({ children }: { children: React.ReactNode }) {
    const { user, isLoading, isPending } = useAuth();
    const router = useRouter();
    const pathname = usePathname();

    const authRoutes = ["/login", "/register", "/reset-password", "/forgot-password"];
    const exceptionalRoutes = ["/otp-verification", "/reset-password"];

    const isAuthRoute = authRoutes.includes(pathname);
    const isExceptionalRoute = exceptionalRoutes.includes(pathname);
    const isPublicRoute = isAuthRoute || isExceptionalRoute;

    useEffect(() => {
        // Unauthenticated access to protected route -> Login
        if (!user && !isLoading && !isAuthRoute && !isExceptionalRoute) {
            router.push("/login");
        }
        // Authenticated access to auth route (e.g., login, register) -> Home
        if (user && !isLoading && isAuthRoute && !isExceptionalRoute) {
            router.push("/");
        }
    }, [user, isLoading, router, pathname, isAuthRoute, isExceptionalRoute]);

    if (isLoading || isPending) {
        return <Loader className="min-h-screen" />
    }
    if (!user && !isAuthRoute && !isExceptionalRoute) {
        return <Loader className="min-h-screen" />
    }


    return (
        <OTPFlowProvider>
            {user ?
                <UserLayout>
                    {children}
                </UserLayout> :
                <>
                    {children}
                </>
            }
        </OTPFlowProvider>
    )
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={cn("font-sans", inter.variable)} suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`} suppressHydrationWarning>
                <Providers>
                    <AuthProvider>
                        <AuthWrapper>
                            {children}
                        </AuthWrapper>
                    </AuthProvider>
                </Providers>
            </body>
        </html>
    );
}
